### ISSUE TITLE
视图信息显示疑问

### ISSUE THREAD

**Issue by JIElite** [wwxFromTju/sc2-101-zh#1]
请问博主这张图的讯息是怎麽提取的？
![image](https://user-images.githubusercontent.com/6872274/32450445-30e89b68-c34f-11e7-80ed-512bf245cbc4.png)

能不能提供具体代码？

感谢

**Comment by wwxFromTju** [comment]
请直接输出对应小的map就可以了

**Comment by JIElite** [comment]
还是不太明瞭

另外，想要请教 obs.observation['screen'] 的组成是如何？
他的 shape 是 (17, 84, 84)，运行 agent 的时候，feature maps 却超过 17 个。博主有研究这 17 代表哪些 features 吗？
